// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session.post').default>>>>
    }
    '/api/talk': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talk.post').default>>>>
    }
    '/api/tts': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tts.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.9_db0@0.3.4_esbuild@0.28.1_ioredis@5.11.1_magicast@0.5.3_nuxt@3.21.9__k6rclb24fd7fc6l42jed5aotmy/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}