// Generated by Nuxt'
import type { Plugin } from "#app";

type Decorate<T extends Record<string, any>> = {
  [K in keyof T as K extends string ? `$${K}` : never]: T[K];
};

type InjectionType<A extends Plugin> = A extends { default: Plugin<infer T> }
  ? Decorate<T>
  : unknown;

type NuxtAppInjections = InjectionType<
  typeof import(
    "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/revive-payload.client.js",
  )
> &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/head/runtime/plugins/unhead.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/pages/runtime/plugins/router.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/payload.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/dev-server-logs.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/revive-payload.server.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/@nuxt+devtools@3.3.1_db0@0.3.4_ioredis@5.11.1_magic-string@0.30.21_oxc-parser@0.140.0_unplugi_6vthfxgqe4eqr3qyzpykscuvy4/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/@nuxt+devtools@3.3.1_db0@0.3.4_ioredis@5.11.1_magic-string@0.30.21_oxc-parser@0.140.0_unplugi_6vthfxgqe4eqr3qyzpykscuvy4/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/warn.dev.server.js",
    )
  > &
  InjectionType<
    typeof import(
      "../../../../node_modules/.pnpm/nuxt@3.21.9_@biomejs+biome@1.9.4_@types+node@22.20.1_@vue+compiler-sfc@3.5.40_cac@6.7.14_db0@_eachidmypsudlfp3yvbkwoxude/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js",
    )
  >;

declare module "#app" {
  interface NuxtApp extends NuxtAppInjections {}

  interface NuxtAppLiterals {
    pluginName:
      | "vue-devtools-client"
      | "nuxt:revive-payload:client"
      | "nuxt:head"
      | "nuxt:router"
      | "nuxt:browser-devtools-timing"
      | "nuxt:payload"
      | "nuxt:revive-payload:server"
      | "nuxt:chunk-reload"
      | "nuxt:global-components"
      | "nuxt:prefetch"
      | "nuxt:checkIfPageUnused"
      | "nuxt:checkIfLayoutUsed";
  }
}

declare module "vue" {
  interface ComponentCustomProperties extends NuxtAppInjections {}
}
